name: tank
channels:
  - defaults
  - conda-forge
dependencies:
  - cython
  - pandas
  - numpy
  - openpyxl
  - sundials
  - assimulo
  - pip
  - pip:
    - matplotlib
    - scipy
    - streamlit-ext

