name: tank
channels:
  - defaults
  - conda-forge
dependencies:
  - cython
  - pandas
  - numpy
  - openpyxl
  - gxx_linux-64
  - assimulo
  - matplotlib
  - scipy
  - pip
  - pip:
    - streamlit-ext

