name: base
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - streamlit
    - scipy
    - matplotlib
    - XlsxWriter
    - openpyxl
    - streamlit-ext
    - Assimulo-3.3-py39-none-any.whl