name: base
channels:
  - conda-forge
dependencies:
  - pip
  - assimulo-3.3-py39h5ec1a66_0.tar.bz2
  - pip:
    - streamlit
    - scipy
    - matplotlib
    - XlsxWriter
    - openpyxl
    - streamlit-ext